### ISSUE TITLE
Rise 1.1.1 issue

### ISSUE THREAD

**Issue by trnpally** [dakk/lisk-pool#30]
lisk-pool$ python3 liskpool.py
To distribute: 0.000000 RISE
Traceback (most recent call last):
  File "liskpool.py", line 216, in <module>
    pool ()
  File "liskpool.py", line 136, in pool
    f = open ('payments.sh', 'w')
PermissionError: [Errno 13] Permission denied: 'payments.sh'

**Comment by trnpally** [comment]
Was working on 1.0.x but is not working on new version of Rise 1.1.1
