### ISSUE TITLE
ValueError: not enough values to unpack

### ISSUE THREAD

**Issue by Stoner19** [dakk/lisk-pool#8]
Any idea why I'm seeing this error?

```To distribute: 0.000000 LISK
Traceback (most recent call last):
  File "liskpool.py", line 168, in <module>
    pool ()
  File "liskpool.py", line 85, in pool
    (topay, log, forged) = estimatePayouts (log)
ValueError: not enough values to unpack (expected 3, got 2)```

**Comment by dakk** [comment]
This is because of a wrong "node" address (it should not end with a /); btw, I inserted a sanity check for this type of error in the new version
